### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by weregod** [luapp-org/luapp#9]
./luappc test.lua
![image](https://user-images.githubusercontent.com/108836174/224313495-32515a68-8d3a-4460-8c92-957efed0705c.png)

[test.lua.txt](https://github.com/luapp-org/luapp/files/10941910/test.lua.txt)

**Comment by weregod** [comment]
if uncomment all code in script compiler stuck in infinite loop

**Comment by maxxprihodko** [comment]
Thanks for finding this. My assumption is that it is related to the type checker not handling functions with no arguments. I will close this once I have fixed the problem.

Here is an example of what runs correctly:
```lua
local function HW(n: number): void
    print(n)
end
```

and a similar example to the one that you provided, will not run and a segfault will follow:
```lua
local function HW(): void
    print(1)
end
```
